name: PyRS
channels:
- conda-forge
- mantid/label/nightly
dependencies:
- python
- anaconda-client
- boa
- mantidworkbench
- qtpy
- pip
- pyqt
- pytest
- pytest-cov
- pytest-qt
- uncertainties
- libarchive
- flake8
- mypy
- matplotlib
- numpy
- pandas
- types-six
- versioningit
- conda-build
- conda-verify
- setuptools
- pip:
  - check-wheel-contents
